# Generated by Django 3.1.5 on 2021-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_strin', models.CharField(max_length=256, verbose_name='Number In Words')),
                ('nds', models.BooleanField(blank=True, default=False, verbose_name='NDS')),
                ('nds_percent', models.IntegerField(blank=True, verbose_name='NDS PERCENT')),
                ('date_in', models.DateTimeField(auto_now_add=True, verbose_name='ADD TIME')),
            ],
            options={
                'verbose_name': 'Numbers',
                'verbose_name_plural': 'Number',
            },
        ),
    ]
