# Generated by Django 3.1.5 on 2021-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_int', models.CharField(max_length=50)),
                ('number_str', models.TextField(blank=True)),
                ('nds', models.BooleanField(blank=True)),
                ('nds_percent', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
