# Generated by Django 3.1.5 on 2021-01-31 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210131_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnumber',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
